Update srpc_generator
sogou/srpc pull request #161
Opened 2022-01-29 13:24 UTC by holmes1412

Add two updates mentioned in this Pull Request: https://github.com/holmes1412/srpc/pull/26

(1) Some redundancy in specifying the input IDL file type
(2) Crash if output directory doesn't exist

Also make it compatible with the original usage and add a version check.

Correct usage: 
```sh
srpc_generator protobuf echo_pb.proto ./
```

```sh
srpc_generator echo_thrift.thrift ./
```

Error usage and message:
```sh
liyingxin@P_QZLIU-MB0 srpc_1412_new % srpc_generator .xxx ./                             
ERROR: Invalid IDL file .xxx
Usage:
	srpc_generator <idl_file> <output_dir>
```

```sh
liyingxin@P_QZLIU-MB0 srpc_1412_new % srpc_generator xxx tutorial/echo_pb.proto ./
ERROR: Invalid IDL type xxx
Usage:
	srpc_generator <idl_file> <output_dir>
```

```sh
liyingxin@P_QZLIU-MB0 srpc_1412_new % srpc_generator --version                    
srpc_generator version 0.9.5
```

```sh
liyingxin@P_QZLIU-MB0 srpc_1412_new % srpc_generator          
Usage:
	srpc_generator <idl_file> <output_dir>
```

2022-01-29 13:29 UTC, holmes1412 commented
@linqigang888 I may need your help to review this Pull Request.
I also wanted to choose you as a reviewer at the REVIEWERS column on the right, but I cannot find your account on the column list.

2022-01-29 15:32 UTC, holmes1412 commented
According to Lance's suggestion,  optargs and getopt_long can make order of arguments won't matter.
I will implement this feature next time.

2022-01-30 09:25 UTC, Barenboim commented on src/generator/compiler.cc
> +		if (strcmp(argv[1], "protobuf") && strcmp(argv[1], "thrift"))
改成strcasecmp吧

2022-01-30 09:25 UTC, Barenboim commented on src/generator/compiler.cc
> +const char *SRPC_GENERATOR_USAGE = "Usage:\n\t%s <idl_file> <output_dir>\n";
这个USAGE改一下，中间加上[protobuf/thrift]这个可选参数

2022-01-30 09:25 UTC, Barenboim commented on src/generator/compiler.cc
> +	idl_type = check_idl_type(argv[idl_file_id]);
如果用户填写了protobuf或thrift，应该就不再判断文件名吧？

2022-01-30 14:21 UTC, holmes1412 commented on src/generator/compiler.cc
> +		if (strcmp(argv[1], "protobuf") && strcmp(argv[1], "thrift"))
ok

2022-01-30 14:21 UTC, holmes1412 commented on src/generator/compiler.cc
> +const char *SRPC_GENERATOR_USAGE = "Usage:\n\t%s <idl_file> <output_dir>\n";
改好了。现在的usage是：
```
srpc_generator [protobuf|thrift] <idl_file> <output_dir>
```

2022-01-30 14:21 UTC, holmes1412 commented on src/generator/compiler.cc
> +	idl_type = check_idl_type(argv[idl_file_id]);
对的，改好了。

2022-01-31 13:48 UTC, linqigang888 commented
Hello,

I think these changes are good! Here are a few comments:

(1) I like the use of the enum for file type, it is more "complete".

(2) I understand using the file extension for determining the IDL type. This can work. Do we assume users will always have the correct file type? That is to say, someone would not realise that their file was .proto but it was named .thrift instead? I think this assumption is fine as your audience is developers and they should know better. You should make sure that srpc_generator exits gracefully in the case of the wrong input file type (extension mismatch) for this situation.

In general, I assume the worst of users and write software to protect against them :)

(3) Future suggestion: my code added a guard against a crash when the output directory did not exist. Perhaps we could create the output directory for the user, should it not exist? I was able to find a cross-platform solution to test if a directory exists (Linux/Windows) but didn't have the time to run down the same code to create a directory in a cross-platform fashion.

(4) When I made my initial PR, it was a "suggestion" type so I'm glad to see you implemented a way to use both the argc "4" version as well as the newer "3" version. This is great for stability and backwards compatibility. If you do implement getopt_long or optargs, I would then revise the code to accept the "4" version (no optarg/getopt_long) or the optarg/getopt_long version for backwards compatibility/legacy support. Once everything is updated, I would fully switch to getopt.

Best,

Lance

2022-02-02 12:55 UTC, holmes1412 commented
@linqigang888 Thank you for your comment!  

(2) About the file extension - Yes, people will realize what their file is. Because the usage of the file extension is the original convention of protobuf and thrift, which means protobuf users can make sure their idl file end with .proto and so as the thrift users.
When the idl type does not match the file extension, srpc_generator will not crash, but exist with error message instead.

(3)  create non-existent directory - This is a good suggestion, but I have the `protoc` and it has not support this feature yet. So I think I will discuss with my colleagues and maybe implement this in the future.

(4) I think argc "3" version is better and less redundancy ~ I will finish the optarg/getopt_long version within this week, the usage will be like: `srpc_generator -i <IDL_FILE> -o <OUTPUT_DIR>`. But it will also support the old argc "4" version: `srpc_generator [protobuf|thirft] <IDL_FILE> <OUTPUT_DIR>`. Is this ok? @Barenboim

2022-02-05 11:18 UTC, Barenboim requested changes
不要引入stat，windows下没有。其实无需判断目录是否存在，直接创建文件查看返回值就可以。
判断文件扩展名的代码应该用strcmp而不是strstr，那个判断逻辑是错的。

2022-02-05 12:28 UTC, Barenboim approved these changes

2022-02-05 12:29 UTC, merged